### ISSUE TITLE
[Discussion - MVVM] Pass data between ViewModels

### ISSUE THREAD

**Issue by jzeferino** [XamarinUniversity/XAM301#1]
hi @markjulmar,

Some times is necessary to pass some data from one `ViewModel` to another.

There are various ways to solve this, eg: 
1 - Pass as parameter;
2 - Use the same ViewModel instance in different screens;
3 - Use some kind of Messaging library like Messaging Center;

Regarding this specific subject, what is you suggestion to solve this when using Dependency Injection for every dependency in the Application.

The scenario is:

You have `EmployeesViewModel` that as a list of `Employees` and its bound to a specific list in the screen.
When a `Employee` is clicked a new screen will be pushed. That screen uses `EmployeDetailViewModel`.

Since all dependencies of ViewModels are solved via Dependency Injection. How do you pass the data from `EmployeesViewModel` to `EmployeDetailViewModel` without using the solutions (1,2 and 3.)?

**Comment by markjulmar** [comment]
As with most discussions about architecture, it depends.. and there are likely several (good) opinions depending on what you prioritize as your core value for the code.

Do the ViewModels have a natural relationship to one another (e.g. is one primarily owned by the other, or are they almost always treated as a single unit?). If so, I have no problem coupling them together and having them hold references. That's simple and efficient. You can still use interfaces to abstract the communication model if you are concerned with objects having too much knowledge about each other (e.g. some kind of `ISupportNotification` interface).

However, if they are generally independent from each other and separate parts of your system, then I'd ask myself if the messaging be done at the _Model_ layer? E.g. is this something that should be occurring below the ViewModel and the ViewModel is reacting to it. If so, then I'd not try to have ViewModels talk to each other, but instead have external forces update the models which would then bubble up to the ViewModels in question.

If none of the above is true, and the state we are talking about is transient or visual in nature, then I'd likely prefer some kind of loosely coupled Mediator or Event Broker pattern (like Messaging Center - but definitely abstract it out!). There are a variety of implementations out there (PRISM has the Event Aggregator, MVVMLight has the Messenger, MVVM, I built a [MessageMediator](https://github.com/markjulmar/mvvmhelpers/blob/master/MvvmHelpers.Portable/JulMar.Core/Services/MessageMediator.cs) class back with my MVVM library in 2009), etc.)

To your specific instance here, `EmployeesViewModel` clearly knows about `Employee`. I'm assuming you are using a command to handle the detail navigation - it seems like you could pretty easily construct the `EmployeeDetailViewModel` just-in-time, passing in the `Employee` that was selected along with any other required data and then invoke whatever service is running your navigation (passing the newly created `EmployeeDetailViewModel` as the parameter to set as the binding context). It's perfectly fine for ViewModels to _share_ model information .. that's actually quite common and allows for different screens to present different visualizations of the same data.

**Comment by jzeferino** [comment]
I agree with what you said. 

But, my question is a bit more specific and I still don't have  a simple answer/solution for it.
Lets stick with the scenario I talked before.

I forget to mention this is not for Xamarin.Forms. This is for a Xamarin.Android and Xamarin.iOS application sharing the same portable code.

To refresh:
We have two screens, Employee list and Employee detail.
Everything in the application is based on IOC (except the ViewControllers and Activitys/Fragments that are solving its dependencies explicitly like `SimpleIOC.Default.GetInstance<X>`) and in this particular case using MVVMLight.

So, `ActivityEmplyeeList` has a reference for `EmployeesViewModel` and when we select an Employee we want to share that Employee with `ActivityEmployeeDetail` that as a reference to `EmployeesDetailViewModel`.

We could use an intent for that but if we do that, we will have to pass the Employee as a parameter in iOS ViewController. But I want that logic to be abstracted in `ViewModel` so the guys that are making the UI don't have to care about passing parameters.

The `ActivityEmployeeDetail` will have a reference to `EmployeesDetailViewModel` but when it calls `SimpleIOC.Default.GetInstance<EmployeesDetailViewModel>` we will need to have the selected Employee somewhere. In this case the Messaging won't work because when `EmployeesViewModel` send the message with the Employee, the `EmployeesDetailViewModel` don't exist yet.

At the moment, Im solving this with a `EmployeeController` that is a class that has the selected Employee and this class is a common (DI) dependency in the two ViewModel.
I could also create a Employee dependency in `EmployeesDetailViewModel` and before navigate to `ActivityEmployeeDetail` register that dependency from the `EmployeesViewModel`.

Hope this was more clear, love you hear your thoughts on that.

**Comment by jzeferino** [comment]
@markjulmar ping.

**Comment by jzeferino** [comment]
@markjulmar ping.

**Comment by patridge** [comment]
Since this discussion is about the course instead of the exercise code contained in this repo, I'm going to close it. The [Xamarin University section of the forums](https://forums.xamarin.com/categories/university) might be a good place for these sorts of meta discussions.
